image: docker
services:
  - docker:dind
stages:
  - build
  - deploy
build: 
  stage: build
  script:
    - env
    - echo glpat-zsGfLs9LNS_bJuL4Jnj4 | docker login -u tgpham26 registry.gitlab.com --password-stdin
    - pwd && ls -la
    - docker build -t registry.gitlab.com/tgpham26/pnhappproject . 
    - docker push registry.gitlab.com/tgpham26/pnhappproject
deploy:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d  '\r' | ssh-add -
    - ssh-keyscan -H $SSH_SERVER_IP_TEST >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - ssh ${SSH_USER}@${SSH_SERVER_IP_TEST} "echo glpat-zsGfLs9LNS_bJuL4Jnj4 | sudo docker login -u tgpham26 registry.gitlab.com --password-stdin"
    - pwd && ls -la
    - ssh ${SSH_USER}@${SSH_SERVER_IP_TEST} "rm -rf docker-compose.yml"
    - scp docker-compose.yml ubuntu@SSH_SERVER_IP_TEST:/home/ubuntu/
    - ssh ${SSH_USER}@${SSH_SERVER_IP_TEST} "pwd && ls -la"
    - ssh ${SSH_USER}@${SSH_SERVER_IP_TEST} "sudo docker-compose down"
    - ssh ${SSH_USER}@${SSH_SERVER_IP_TEST} "echo 'sudo docker-compose up -d' | bash -s &"
























