appproject:
 image: docker
 services:
  - docker:dind
 script:
  - env
  - echo glpat-w-LK6RG_zPMSo6cL9b6S | docker login -u tgpham26 registry.gitlab.com --password-stdin
  - docker build -t registry.gitlab.com/tgpham26/pnhappproject .
  - docker push registry.gitlab.com/tgpham26/pnhappproject
