appproject:
 image: docker
 services:
  - docker:dind
 scripts:
  - env
  - echo glpat-5NyEyKXjGByjg1E6gYux | docker login -u abc registry.gitlab.com --password-stdin
  - docker build -t registry.gitlab.com/tgpham26/pnhappproject .
  - docker push registry.gitlab.com/tgpham26/pnhappproject
